In [1]:
import torch

In [2]:
x = torch.rand(2,3)

In [3]:
x

tensor([[0.9114, 0.0638, 0.0083],
        [0.5824, 0.5664, 0.6754]])

In [5]:
#正态分布
x = torch.randn(3,4)

In [6]:
x

tensor([[ 0.1254,  1.7020, -1.7435,  0.7784],
        [ 0.8048, -1.0764, -0.7138,  3.0309],
        [-0.4887, -0.3859,  0.4337,  2.5931]])

In [7]:
#全零/全1的数组
x = torch.zeros(2,3)

In [8]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
x = torch.ones((2,3,4),dtype =torch.int32)

In [20]:
x

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int32)

In [21]:
x.size()

torch.Size([2, 3, 4])

In [22]:
x.size(2)

4

In [23]:
x = torch.tensor([6,2],dtype=torch.float32)

In [24]:
x

tensor([6., 2.])

In [25]:
x.type()

'torch.FloatTensor'

In [26]:
x.type(torch.int64)   #数据类型的转换

tensor([6, 2])

tensor与ndarray数据类型的转换

In [28]:
import numpy as np

In [30]:
a = np.random.randn(2,3)

In [31]:
a

array([[ 1.77376051, -0.45074691,  1.74325065],
       [-0.62185977, -1.79072334, -0.615108  ]])

In [32]:
x1 = torch.from_numpy(a)

In [33]:
x1

tensor([[ 1.7738, -0.4507,  1.7433],
        [-0.6219, -1.7907, -0.6151]], dtype=torch.float64)

In [34]:
x1.numpy()

array([[ 1.77376051, -0.45074691,  1.74325065],
       [-0.62185977, -1.79072334, -0.615108  ]])

In [35]:
x1

tensor([[ 1.7738, -0.4507,  1.7433],
        [-0.6219, -1.7907, -0.6151]], dtype=torch.float64)

In [36]:
x2 = torch.rand(2,3)

In [37]:
x2

tensor([[0.8699, 0.1955, 0.4433],
        [0.1277, 0.6593, 0.4370]])

In [38]:
x1 + x2

tensor([[ 2.6437, -0.2552,  2.1865],
        [-0.4942, -1.1314, -0.1782]], dtype=torch.float64)

In [39]:
x1 + 3

tensor([[4.7738, 2.5493, 4.7433],
        [2.3781, 1.2093, 2.3849]], dtype=torch.float64)

In [40]:
x1.add(x2)

tensor([[ 2.6437, -0.2552,  2.1865],
        [-0.4942, -1.1314, -0.1782]], dtype=torch.float64)

In [41]:
x1.add_(x2)

tensor([[ 2.6437, -0.2552,  2.1865],
        [-0.4942, -1.1314, -0.1782]], dtype=torch.float64)

In [42]:
x1

tensor([[ 2.6437, -0.2552,  2.1865],
        [-0.4942, -1.1314, -0.1782]], dtype=torch.float64)

In [43]:
x1.shape

torch.Size([2, 3])

In [44]:
x1.view(3,2)

tensor([[ 2.6437, -0.2552],
        [ 2.1865, -0.4942],
        [-1.1314, -0.1782]], dtype=torch.float64)

In [45]:
x1

tensor([[ 2.6437, -0.2552,  2.1865],
        [-0.4942, -1.1314, -0.1782]], dtype=torch.float64)

In [46]:
x1.view(-1,1)    #shape (n,1)

tensor([[ 2.6437],
        [-0.2552],
        [ 2.1865],
        [-0.4942],
        [-1.1314],
        [-0.1782]], dtype=torch.float64)

In [47]:
x1

tensor([[ 2.6437, -0.2552,  2.1865],
        [-0.4942, -1.1314, -0.1782]], dtype=torch.float64)

In [48]:
x1.mean()

tensor(0.4619, dtype=torch.float64)

In [51]:
x = x1.sum()

In [52]:
x

tensor(2.7712, dtype=torch.float64)

In [53]:
x.item()

2.771170497188681

# 张量的自动微分
将Torch.Tensor属性.require_grad设置为True
pytorch将开始跟踪对此张量的所有操作
完成计算后,可以调用.backward()并自动计算所有数据
该张量的梯度将累加到.grad属性中


In [55]:
x = torch.ones(2,2,requires_grad = True)

In [56]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [57]:
x.requires_grad

True

In [58]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [59]:
x.grad

In [60]:
x.grad_fn

In [61]:
y = x + 2

In [62]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [63]:
y.grad_fn

In [64]:
z = y * y + 3

In [65]:
out = z.mean()

In [66]:
z

tensor([[12., 12.],
        [12., 12.]], grad_fn=<AddBackward0>)

In [67]:
out

tensor(12., grad_fn=<MeanBackward0>)

In [68]:
out.backward()

out = f(x)
d out/dx

In [69]:
x.grad

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])

In [70]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [71]:
with torch.no_grad():
    print((x**2).requires_grad)

False


In [72]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [73]:
(x**2).requires_grad

True

In [74]:
y = x.detach()

In [75]:
y

tensor([[1., 1.],
        [1., 1.]])

In [76]:
y.requires_grad

False

In [81]:
a = torch.tensor([2,3],dtype = torch.float32)

In [78]:
a

tensor([2, 3])

In [79]:
a.requires_grad

False

In [82]:
a.requires_grad_(True)

tensor([2., 3.], requires_grad=True)

In [83]:
a

tensor([2., 3.], requires_grad=True)