In [1]:
import torch 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [3]:
data = pd.read_csv('data/HR.csv')

In [4]:
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years   part  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   Work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   part                   14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [6]:
data.part.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [7]:
data.salary.unique()

array(['low', 'medium', 'high'], dtype=object)

In [8]:
data.groupby(['salary','part']).size()

salary  part       
high    IT               83
        RandD            51
        accounting       74
        hr               45
        management      225
        marketing        80
        product_mng      68
        sales           269
        support         141
        technical       201
low     IT              609
        RandD           364
        accounting      358
        hr              335
        management      180
        marketing       402
        product_mng     451
        sales          2099
        support        1146
        technical      1372
medium  IT              535
        RandD           372
        accounting      335
        hr              359
        management      225
        marketing       376
        product_mng     383
        sales          1772
        support         942
        technical      1147
dtype: int64

In [11]:
data = data.join(pd.get_dummies(data.salary))

In [12]:
del data['salary']

In [13]:
data = data.join(pd.get_dummies(data.part))

In [14]:
del data['part']

In [15]:
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  high  low  \
0                   3              0     1                      0     0    1   
1                   6              0     1                      0     0    0   
2                   4              0     1                      0     0    0   
3                   5              0     1                      0     0    1   
4                   3              0     1                      0     0    1   

   ...  IT  RandD  accounting  hr  management  marketing  product_mng  sales  \
0  ...   0      0           0   0           0          0            0      1   
1  ...   0      0           0   0           0          0            0      1   
2  ...   0      0           0   0           0          0            0      1   
3  ...   0      0           0   0           0          0            0      1   
4  ...   0      0           0   0           0          0            0      1   

   support  technical  
0        0          0  
1        0          0  
2        0          0  
3        0          0  
4        0          0  

[5 rows x 21 columns]

In [16]:
data

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years  high  low  ...  IT  RandD  accounting  hr  \
0                          0     0    1  ...   0      0           0   0   
1                          0     0    0  ...   0      0           0   0   
2                          0     0    0  ...   0      0           0   0   
3                          0     0    1  ...   0      0           0   0   
4                          0     0    1  ...   0      0           0   0   
...                      ...   ...  ...  ...  ..    ...         ...  ..   
14994                      0     0    1  ...   0      0           0   0   
14995                      0     0    1  ...   0      0           0   0   
14996                      0     0    1  ...   0      0           0   0   
14997                      0     0    1  ...   0      0           0   0   
14998                      0     0    1  ...   0      0           0   0   

       management  marketing  product_mng  sales  support  technical  
0               0          0            0      1        0          0  
1               0          0            0      1        0          0  
2               0          0            0      1        0          0  
3               0          0            0      1        0          0  
4               0          0            0      1        0          0  
...           ...        ...          ...    ...      ...        ...  
14994           0          0            0      0        1          0  
14995           0          0            0      0        1          0  
14996           0          0            0      0        1          0  
14997           0          0            0      0        1          0  
14998           0          0            0      0        1          0  

[14999 rows x 21 columns]

In [17]:
data.left.value_counts()

0    11428
1     3571
Name: left, dtype: int64

In [28]:
11428/len(data)

0.7619174611640777

In [29]:
Y_data = data.left.values.reshape(-1,1)

In [30]:
Y_data.shape

(14999, 1)

In [34]:
Y = torch.from_numpy(Y_data).type(torch.FloatTensor)

In [38]:
X_data = data[[c for c in data.columns if c != 'left']].values

In [39]:
X = torch.from_numpy(X_data).type(torch.FloatTensor)

In [40]:
X.size()

torch.Size([14999, 20])

In [42]:
Y.shape

torch.Size([14999, 1])

创建模型

In [43]:
from torch import nn

#自定义模型
nn.module:   #基础
__init__:    #初始化所有的层
forward:     #定义模型的运算过程 (前向传播的过程)

In [44]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.liner_1 = nn.Linear(20, 64)
        self.liner_2 = nn.Linear(64, 64)
        self.liner_3 = nn.Linear(64, 1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
    def forward(self,input):
        x = self.liner_1(input)
        x = self.relu(x)
        x = self.liner_2(x)
        x = self.relu(x)
        x = self.liner_3(x)
        x = self.sigmoid(x)
        return x

In [45]:
model = Model()

In [50]:
model

Model(
  (liner_1): Linear(in_features=20, out_features=64, bias=True)
  (liner_2): Linear(in_features=64, out_features=64, bias=True)
  (liner_3): Linear(in_features=64, out_features=1, bias=True)
)

改写模型

In [46]:
import torch.nn.functional as F

In [47]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.liner_1 = nn.Linear(20, 64)
        self.liner_2 = nn.Linear(64, 64)
        self.liner_3 = nn.Linear(64, 1)
    def forward(self,input):
        x = F.relu(self.liner_1(input))
        x = F.relu(self.liner_2(x))
        x = F.sigmoid(self.liner_3(x))
        return x

In [48]:
model = Model()

In [49]:
model

Model(
  (liner_1): Linear(in_features=20, out_features=64, bias=True)
  (liner_2): Linear(in_features=64, out_features=64, bias=True)
  (liner_3): Linear(in_features=64, out_features=1, bias=True)
)

In [51]:
lr = 0.0001

In [52]:
def get_model():
    model = Model()
    opt = torch.optim.Adam(model.parameters(),lr = lr)
    return model,opt

In [53]:
model,optim = get_model()

定义损失函数

In [54]:
loss_fn = nn.BCELoss()

In [57]:
batch = 64
no_of_batches = len(data)//batch
epoches  = 100

In [61]:
for epoch in range(epoches):
    for i in range(no_of_batches):
        start = i * batch
        end = start + batch
        x = X[start:end]
        y = Y[start:end]
        y_pred = model(x)
        loss = loss_fn(y_pred,y)
        optim.zero_grad()
        loss.backward()
        optim.step()
    with torch.no_grad():
        print('epoch:',epoch,'loss:',loss_fn(model(X),Y).data.item())
    

epoch: 0 loss: 0.5050098896026611
epoch: 1 loss: 0.504662275314331
epoch: 2 loss: 0.5026178359985352
epoch: 3 loss: 0.5027983784675598
epoch: 4 loss: 0.5001523494720459
epoch: 5 loss: 0.4984411597251892
epoch: 6 loss: 0.49759751558303833
epoch: 7 loss: 0.49657002091407776
epoch: 8 loss: 0.4954419732093811
epoch: 9 loss: 0.4930681884288788
epoch: 10 loss: 0.49282726645469666
epoch: 11 loss: 0.49089717864990234
epoch: 12 loss: 0.4902932643890381
epoch: 13 loss: 0.48877665400505066
epoch: 14 loss: 0.4878871738910675
epoch: 15 loss: 0.48693984746932983
epoch: 16 loss: 0.48580920696258545
epoch: 17 loss: 0.4841900169849396
epoch: 18 loss: 0.4831245243549347
epoch: 19 loss: 0.48186028003692627
epoch: 20 loss: 0.48098641633987427
epoch: 21 loss: 0.47992926836013794
epoch: 22 loss: 0.478645384311676
epoch: 23 loss: 0.47651126980781555
epoch: 24 loss: 0.4755847454071045
epoch: 25 loss: 0.4746263027191162
epoch: 26 loss: 0.4732291102409363
epoch: 27 loss: 0.47287240624427795
epoch: 28 loss: 0.47

使用dataset类进行重构

In [62]:
from torch.utils.data import TensorDataset

In [63]:
HRdataset = TensorDataset(X,Y)

In [64]:
HRdataset

In [65]:
len(HRdataset)

14999

In [67]:
HRdataset[0]

(tensor([  0.3800,   0.5300,   2.0000, 157.0000,   3.0000,   0.0000,   0.0000,
           0.0000,   1.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   1.0000,   0.0000,   0.0000]),
 tensor([1.]))

In [68]:
HRdataset[2:5]

(tensor([[1.1000e-01, 8.8000e-01, 7.0000e+00, 2.7200e+02, 4.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
          0.0000e+00, 0.0000e+00],
         [7.2000e-01, 8.7000e-01, 5.0000e+00, 2.2300e+02, 5.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
          0.0000e+00, 0.0000e+00],
         [3.7000e-01, 5.2000e-01, 2.0000e+00, 1.5900e+02, 3.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
          0.0000e+00, 0.0000e+00]]),
 tensor([[1.],
         [1.],
         [1.]]))

In [69]:
model,optim = get_model()

In [70]:
for epoch in range(epoches):
    for i in range(no_of_batches):
        x, y = HRdataset[i * batch: i*batch+batch]
        y_pred = model(x)
        loss = loss_fn(y_pred,y)
        optim.zero_grad()
        loss.backward()
        optim.step()
    with torch.no_grad():
        print('epoch:',epoch,'loss:',loss_fn(model(X),Y).data.item())

epoch: 0 loss: 0.7106070518493652
epoch: 1 loss: 0.7259021401405334
epoch: 2 loss: 0.7270771861076355
epoch: 3 loss: 0.7227984070777893
epoch: 4 loss: 0.7119989395141602
epoch: 5 loss: 0.7036832571029663
epoch: 6 loss: 0.690563976764679
epoch: 7 loss: 0.6812061071395874
epoch: 8 loss: 0.6711769700050354
epoch: 9 loss: 0.6481488943099976
epoch: 10 loss: 0.6359529495239258
epoch: 11 loss: 0.627331554889679
epoch: 12 loss: 0.6187276244163513
epoch: 13 loss: 0.6104666590690613
epoch: 14 loss: 0.6025253534317017
epoch: 15 loss: 0.5951630473136902
epoch: 16 loss: 0.588044285774231
epoch: 17 loss: 0.5816576480865479
epoch: 18 loss: 0.5759221315383911
epoch: 19 loss: 0.5708535313606262
epoch: 20 loss: 0.5686362981796265
epoch: 21 loss: 0.5690157413482666
epoch: 22 loss: 0.563781201839447
epoch: 23 loss: 0.5614559650421143
epoch: 24 loss: 0.5614914298057556
epoch: 25 loss: 0.5615995526313782
epoch: 26 loss: 0.5617489218711853
epoch: 27 loss: 0.5619950294494629
epoch: 28 loss: 0.5621839761734009

 dataloader类

In [71]:
from torch.utils.data import DataLoader

In [75]:
HR_ds = TensorDataset(X, Y)
HR_dl = DataLoader(HR_ds,batch_size = batch,shuffle = True)

In [76]:
model,optim = get_model()

In [77]:
for epoch in range(epoches):
    for x,y in HR_dl:
        y_pred = model(x)
        loss = loss_fn(y_pred,y)
        optim.zero_grad()
        loss.backward()
        optim.step()
    with torch.no_grad():
        print('epoch:',epoch,'loss:',loss_fn(model(X),Y).data.item())

epoch: 0 loss: 0.5626465678215027
epoch: 1 loss: 0.561223030090332
epoch: 2 loss: 0.556711733341217
epoch: 3 loss: 0.5546606183052063
epoch: 4 loss: 0.5495873093605042
epoch: 5 loss: 0.5503899455070496
epoch: 6 loss: 0.5417469143867493
epoch: 7 loss: 0.5370489358901978
epoch: 8 loss: 0.532516360282898
epoch: 9 loss: 0.5286435484886169
epoch: 10 loss: 0.5251564383506775
epoch: 11 loss: 0.5177542567253113
epoch: 12 loss: 0.5124660730361938
epoch: 13 loss: 0.515972375869751
epoch: 14 loss: 0.4990144670009613
epoch: 15 loss: 0.49341779947280884
epoch: 16 loss: 0.4863510727882385
epoch: 17 loss: 0.4833926558494568
epoch: 18 loss: 0.4720649719238281
epoch: 19 loss: 0.4754544496536255
epoch: 20 loss: 0.45993277430534363
epoch: 21 loss: 0.45453140139579773
epoch: 22 loss: 0.4466542899608612
epoch: 23 loss: 0.4429296553134918
epoch: 24 loss: 0.4471398591995239
epoch: 25 loss: 0.4330584406852722
epoch: 26 loss: 0.4274766147136688
epoch: 27 loss: 0.421094685792923
epoch: 28 loss: 0.41693821549415

 添加验证
 了解过拟合和欠拟合

过拟合:对于训练数据过度拟合,对于未知数据预测很差
欠拟合:对于训练数据拟合不够,对于未知数据预测很差
sklearn   pip install sklearn

In [79]:
from sklearn.model_selection import train_test_split

In [81]:
train_x,test_x,train_y,test_y = train_test_split(X_data,Y_data)

In [85]:
type(train_x)

numpy.ndarray

In [86]:
train_x = torch.from_numpy(train_x).type(torch.float32)
train_y = torch.from_numpy(train_y).type(torch.float32)
test_x = torch.from_numpy(test_x).type(torch.float32)
test_y = torch.from_numpy(test_y).type(torch.float32)

In [82]:
X_data.shape

(14999, 20)

In [84]:
train_x.shape,test_x.shape,train_y.shape

((11249, 20), (3750, 20), (11249, 1))

In [87]:
train_ds = TensorDataset(train_x, train_y)
train_dl = DataLoader(train_ds,batch_size = batch,shuffle = True)

In [89]:
test_ds = TensorDataset(test_x, test_y)
test_dl = DataLoader(test_ds,batch_size = batch)

如何计算正确率

Y_pred = (y_pred > 0.5).type(torch.int32)
(y_pred == labels).float().mean()     #[True,False,True]

In [94]:
def accuracy(y_pred,y_true):
    y_pred = (y_pred > 0.5).type(torch.int32)
    acc = (y_pred == y_true).float().mean()
    return acc

In [95]:
model,optim = get_model()

In [102]:
for epoch in range(epoches):
    for x,y in train_dl:
        y_pred = model(x)
        loss = loss_fn(y_pred,y)
        optim.zero_grad()
        loss.backward()
        optim.step()
    with torch.no_grad():
        epoch_accuracy = accuracy(model(train_x),train_y)
        epoch_loss = loss_fn(model(train_x),train_y).data
        
        epoch_test_accuracy = accuracy(model(test_x),test_y)
        epoch_test_loss = loss_fn(model(test_x),test_y).data
        print('epoch:',epoch,'loss:',round(epoch_loss.item(),3),
                             'accuracy:',round(epoch_accuracy.item(),3),
                             'test_loss:',round(epoch_test_loss.item(),3),
                             'test_accuracy:',round(epoch_test_accuracy.item(),3),
             )

epoch: 0 loss: 0.215 accuracy: 0.928 test_loss: 0.191 test_accuracy: 0.935
epoch: 1 loss: 0.243 accuracy: 0.904 test_loss: 0.218 test_accuracy: 0.913
epoch: 2 loss: 0.227 accuracy: 0.915 test_loss: 0.205 test_accuracy: 0.923
epoch: 3 loss: 0.232 accuracy: 0.912 test_loss: 0.211 test_accuracy: 0.921
epoch: 4 loss: 0.214 accuracy: 0.929 test_loss: 0.192 test_accuracy: 0.934
epoch: 5 loss: 0.213 accuracy: 0.93 test_loss: 0.189 test_accuracy: 0.939
epoch: 6 loss: 0.233 accuracy: 0.911 test_loss: 0.21 test_accuracy: 0.918
epoch: 7 loss: 0.217 accuracy: 0.932 test_loss: 0.193 test_accuracy: 0.937
epoch: 8 loss: 0.217 accuracy: 0.933 test_loss: 0.193 test_accuracy: 0.936
epoch: 9 loss: 0.214 accuracy: 0.932 test_loss: 0.191 test_accuracy: 0.938
epoch: 10 loss: 0.214 accuracy: 0.929 test_loss: 0.191 test_accuracy: 0.935
epoch: 11 loss: 0.214 accuracy: 0.932 test_loss: 0.191 test_accuracy: 0.94
epoch: 12 loss: 0.218 accuracy: 0.931 test_loss: 0.194 test_accuracy: 0.937
epoch: 13 loss: 0.223 acc